name: 自动更新 README 日期
on:
  schedule:
    - cron: '0 16 * * *'  # UTC 时间，北京时间需 +8 小时
  workflow_dispatch:
jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name:  checkout 代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: 修改 README 日期
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d")
          sed -i "s/<!-- 自动更新日期：开始 -->.*<!-- 自动更新日期：结束 -->/<!-- 自动更新日期：开始 -->\n最后更新时间：$CURRENT_DATE\n<!-- 自动更新日期：结束 -->/g" README.md
      - name: 提交并推送修改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动更新 README 日期至 ${CURRENT_DATE}"
          file_pattern: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
